# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-18
# Copyright  : Copyright (C) 2016-2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mysql-data/Dockerfile-x86
# Version    : 1.0.0
# Author     : Bjorn Kjeholt
# *************************************************************************

FROM alpine:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN mkdir -p /var/lib/mysql

VOLUME ["/var/lib/mysql"]
